post_upgrade() {
  if findmnt --fstab -uno SOURCE /boot &>/dev/null && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi
  if (( $(vercmp $2 5.5.8-2) < 0 )); then
    echo '==> Fallback initramfs is not used, so it is being deleted now.'
    rm -f boot/initramfs-%PKGBASE%-fallback.img
  fi
}

post_remove() {
  rm -f boot/initramfs-%PKGBASE%.img
}
